spring:

  application:
    name: springboot-jwt
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot1
    password: 03100310+a
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off

server:
  port: 8081

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true


config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567abcdefg1234567abcdefg1234567abcdefg1234567abcdefg1234567abcdefg1234567abcdefg1234567abcdefg1234567
    # token有效时长
    expire: 3600
    # header 名称
    header: token
